# Run tests on any Go file change
**/*.go {
    prep: go test ./...
}

# Build the app on any Go file change
**/*.go {
    prep: go build -o bin/app ./cmd
}

# Build and restart the app if config files change
**/*.yml **/*.env {
    prep: go build -o bin/app ./cmd
}

# Restart the app on build
bin/app {
    daemon +sigterm: ./bin/app
}